cache:
  paths:
    - subprojects/packagecache/

before_script:
  - ./tools/clean.sh meson

image: greenaddress/ci@sha256:a8589f9da893a50a401296234e9426a31a31f33e3b8c4478ea070e7b455112b5

.fedora_images:
  image: greenaddress/fedora_ci@sha256:01c66f5905debff4fb0b4c613b1ab437010c28cde44572c0bcce34f678fb0fa8
  tags:
    - ga

.ndk_release:
  tags:
    - ga
  artifacts:
    expire_in: 1 day
    when: on_success
    paths:
    - gdk-android-jni

.osx_test:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/

.py_release:
  tags:
    - ga
  before_script:
    - mkdir $CI_PROJECT_DIR/gdk-python
  artifacts:
    expire_in: 1 day
    when: on_success
    paths:
    - gdk-python

test_gcc:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --gcc

release_py3m_stretch:
  extends: .py_release
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --install $PWD/gdk-python --gcc --python-version 3.5

release_py3m_fedora:
  extends: .py_release
  image: greenaddress/fedora_ci@sha256:01c66f5905debff4fb0b4c613b1ab437010c28cde44572c0bcce34f678fb0fa8
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --install $PWD/gdk-python --gcc --python-version 3.7

release_py3m_osx:
  extends: .py_release
  tags:
    - osx
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --install $PWD/gdk-python --clang --python-version 3.7

test_fedora_gcc:
  extends: .fedora_images
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --gcc

test_fedora_clang:
  extends: .fedora_images
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --clang

test_clang:
  tags:
    - ga
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --clang-tidy-version=3.8 --clang
    - ./tools/format.sh && git diff --exit-code



gdk_clang_ndk_armeabi-v7a:
  extends: .ndk_release
  script:
    - cd $CI_PROJECT_DIR
    - mkdir gdk-android-jni
    - ANDROID_NDK=/android-ndk-r19c ./tools/build.sh --install $PWD/gdk-android-jni --ndk armeabi-v7a

gdk_clang_ndk_arm64-v8a:
  extends: .ndk_release
  script:
    - cd $CI_PROJECT_DIR
    - mkdir gdk-android-jni
    - ANDROID_NDK=/android-ndk-r19c ./tools/build.sh --install $PWD/gdk-android-jni --ndk arm64-v8a

gdk_clang_ndk_x86:
  extends: .ndk_release
  script:
    - cd $CI_PROJECT_DIR
    - mkdir gdk-android-jni
    - ANDROID_NDK=/android-ndk-r19c ./tools/build.sh --install $PWD/gdk-android-jni --ndk x86

gdk_clang_ndk_x86_64:
  extends: .ndk_release
  script:
    - cd $CI_PROJECT_DIR
    - mkdir gdk-android-jni
    - ANDROID_NDK=/android-ndk-r19c ./tools/build.sh --install $PWD/gdk-android-jni --ndk x86_64

test_osx_clang:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --lto=false --clang

test_osx_ios:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --lto=false --iphone static

test_osx_ios_sim:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --lto=false --iphonesim static

test_osx_clang_ndk_armeabi-v7a:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk armeabi-v7a

test_osx_clang_ndk_arm64-v8a:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk arm64-v8a

test_osx_clang_ndk_x86:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk x86

test_osx_clang_ndk_x86_64:
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --ndk x86_64

test_freebsd_gcc:
  tags:
    - freebsd
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --gcc

test_freebsd_clang:
  tags:
    - freebsd
  before_script:
    - export PATH="/usr/local/llvm60/bin:$PATH"
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --clang

test_windows_mingw_w64_cross:
  tags:
    - ga
  artifacts:
    expire_in: 1 hour
    when: on_success
    paths:
    - build-windows-mingw-w64/src/libgreenaddress*
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/build.sh --mingw-w64

apidocs:
  tags:
    - ga
  artifacts:
    expire_in: 14 days
    when: on_success
    paths:
    - apidocs.tar.gz
  script:
    - cd $CI_PROJECT_DIR
    - tools/clean.sh
    - virtualenv -p python3 .venv
    - source .venv/bin/activate
    - pip3 install sphinx sphinx_rtd_theme
    - sphinx-build -b html -a -c docs/source docs/source docs/build/html
    - cd docs/build && tar czf ../../apidocs.tar.gz html/ && cd ../..
    - deactivate
    - tools/clean.sh

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/gdk_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - find gdk-android-jni -name "*.a" -type f -delete
    - mkdir gdk_dist
    - tar -czf gdk_dist/gdk-android-jni.tar.gz gdk-android-jni --remove-files
    - mv gdk-python/*whl gdk_dist/
    - cd gdk_dist
    - /opt/process_release
  dependencies:
  - gdk_clang_ndk_armeabi-v7a
  - gdk_clang_ndk_arm64-v8a
  - gdk_clang_ndk_x86
  - gdk_clang_ndk_x86_64
  - release_py3m_stretch
  - release_py3m_fedora
  - release_py3m_osx
  - apidocs
