language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=greenaddress/ci
    - DOCKERHASH=a8589f9da893a50a401296234e9426a31a31f33e3b8c4478ea070e7b455112b5
    - COMPILER=gcc
  matrix:
    - UNUSED=true
    - COMPILER=clang
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=01c66f5905debff4fb0b4c613b1ab437010c28cde44572c0bcce34f678fb0fa8
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=01c66f5905debff4fb0b4c613b1ab437010c28cde44572c0bcce34f678fb0fa8 COMPILER=clang


script:
  - docker run -v $PWD:/gdk $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk && ./tools/build.sh --$COMPILER"
