language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=greenaddress/ci
    - DOCKERHASH=a8589f9da893a50a401296234e9426a31a31f33e3b8c4478ea070e7b455112b5
    - COMPILER=gcc
  matrix:
    - UNUSED=true
    - COMPILER=clang
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=3d710f476b3d44376acc9fca6e26129e954053834f09ad4327756d67a232bd47
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=3d710f476b3d44376acc9fca6e26129e954053834f09ad4327756d67a232bd47 COMPILER=clang


script:
  - docker run -v $PWD:/gdk $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk && ./tools/build.sh --$COMPILER"
