language: generic
sudo: required
addons:
  homebrew:
    update: true
    packages:
      - autoconf@2.13
      - gnu-getopt
      - gnu-sed
      - gnu-tar
      - libtool
      - ninja
      - pkg-config
      - python3
      - swig
      - wget
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      install:
        - python3 -m pip install virtualenv meson===0.58.0
        - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.49.0
      script:
        - source $HOME/.cargo/env && ./tools/build.sh --clang --python-version $(python3 --version | cut -d ' ' -f 2 | cut -d '.' -f1,2) --enable-rust
    - services:
        - docker
      script: docker run -v $PWD:/gdk greenaddress/ci@sha256:a777c4526ae84f6f972665aa1c4e7a44c0325883965b58631811066bd8c1a7ee /bin/bash -c "cd /gdk && ./tools/format.sh && git diff --exit-code && ./tools/build.sh --clang --enable-rust"
    - services:
        - docker
      script: docker run -v $PWD:/gdk greenaddress/ci@sha256:a777c4526ae84f6f972665aa1c4e7a44c0325883965b58631811066bd8c1a7ee /bin/bash -c "cd /gdk && ./tools/build.sh --mingw-w64 --enable-rust"
    - services:
        - docker
      script: docker run -v $PWD:/gdk greenaddress/ci@sha256:a777c4526ae84f6f972665aa1c4e7a44c0325883965b58631811066bd8c1a7ee /bin/bash -c "cd /gdk && ./tools/build.sh --gcc --enable-rust"
    - services:
        - docker
      script: docker run -v $PWD:/gdk greenaddress/fedora_ci@sha256:da48654c02d38c570811fd42b7e2dabc5ac2ca91854982be9544c19b659e8abb /bin/bash -c "cd /gdk && ./tools/build.sh --gcc --enable-rust"
    - services:
        - docker
      script: docker run -v $PWD:/gdk greenaddress/fedora_ci@sha256:da48654c02d38c570811fd42b7e2dabc5ac2ca91854982be9544c19b659e8abb /bin/bash -c "cd /gdk && ./tools/build.sh --clang --enable-rust"
    - services:
        - docker
      script: docker run -v $PWD:/gdk greenaddress/ci@sha256:a777c4526ae84f6f972665aa1c4e7a44c0325883965b58631811066bd8c1a7ee /bin/bash -c "cd /gdk && ./tools/build.sh --gcc --enable-rust"
