language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKERBUILDER=greenaddress/ci
    - DOCKERHASH=8e5e60d4be4736718a9392cea0f2d9ded2b81a339fc41f9c2bfa1e34496ffae7
    - COMPILER=gcc
  matrix:
    - UNUSED=true
    - COMPILER=clang
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=51894754af5c061933e3550fdd582eb3ff9145dd7c72f4a376e6cb77ec7a1420
    - DOCKERBUILDER=greenaddress/fedora_ci DOCKERHASH=51894754af5c061933e3550fdd582eb3ff9145dd7c72f4a376e6cb77ec7a1420 COMPILER=clang
    - DOCKERHASH=670c5f45be29ac727231b6580f57225ec6b82adf6a8dc19074cb5dfc1b644c6f


script:
  - docker run -v $PWD:/gdk $DOCKERBUILDER@sha256:$DOCKERHASH /bin/bash -c "cd /gdk && ./tools/build.sh --$COMPILER"
