[package]
name = "gdk-common"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "William Casarin <jb55@jb55.com>"]
edition = "2018"

[features]
testing = []

[dependencies]
aes-gcm-siv = "0.10"
bitcoin = { version = "0.28", features = ["use-serde"] }
elements = { version = "0.19", features = ["serde-feature"] }
libc = "0.2"
log = "0.4.8"
rand = "0.6.5"
ureq = { version = "2.4.0", features = ["json", "socks-proxy", "gzip", "brotli"] }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
strum = "0.24"
strum_macros = "0.24"
tempfile = "3.2"
