# CI builder images only on changes to their Dockerfiles or tags?
build_gdk_debian_ci:
  extends: .build_setup
  variables:
    IMAGE: blockstream/gdk-debian-ci
    DOCKERFILE: tools/Dockerfile
    DEPS_SH: tools/bullseye_deps.sh
    ENV_FILE: tools/env.sh

build_gdk_builder_ubuntu:
  extends: .build_setup
  variables:
    IMAGE: blockstream/gdk-ubuntu-builder
    DOCKERFILE: tools/Dockerfile_ubuntu_20.04
    DEPS_SH: tools/ubuntu_20.04_deps.sh

build_gdk_builder_fedora:
  extends: .build_setup
  variables:
    IMAGE: blockstream/gdk-fedora-builder
    DOCKERFILE: tools/Dockerfile_fedora32
    DEPS_SH: tools/fedora32_deps.sh
