# CI builder images only on changes to their Dockerfiles or tags?
build_gdk-debian-ci:
  extends: .build_setup
  variables:
    IMAGE: blockstream/gdk-debian-ci
    DOCKER_BUILD_CONTEXT: docker/debian
    ENV_FILE: tools/env.sh

build_gdk-ubuntu-builder:
  extends: .build_setup
  variables:
    IMAGE: blockstream/gdk-ubuntu-builder
    DOCKER_BUILD_CONTEXT: docker/ubuntu

build_gdk-fedora-builder:
  extends: .build_setup
  variables:
    IMAGE: blockstream/gdk-fedora-builder
    DOCKER_BUILD_CONTEXT: docker/fedora
