[package]
name = "gdk_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = { version = "0.28", features = [ "use-serde" ] }
electrsd = { version = "0.20", features = [ "legacy" ] }
electrum-client = { version = "=0.11.0", default-features = false, features = [ "proxy", "use-openssl" ] }
elements = { version = "0.19", features = ["serde-feature"] }
env_logger = "0.9.0"
gdk-electrum = { path = "../gdk_electrum", features = ["testing"] }
gdk-common = { path = "../gdk_common" }
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.2.0"
