[package]
name = "gdk-test"
version = "0.1.0"
edition = "2021"

[dependencies]
electrsd = { version = "0.23.0", features = [ "legacy" ] }
electrum-client = { version = "0.12.0", default-features = false, features = [ "proxy", "use-openssl" ] }
env_logger = "0.10.0"
gdk-common = { path = "../gdk_common" }
gdk-electrum = { path = "../gdk_electrum", features = ["testing"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.2.0"
