[workspace]

members = [
    "gdk_common",
    "gdk_electrum",
    "gdk_rust",
]


[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
incremental = false

# FIXME: LTO is required to fix building on iphone
[profile.dev]
# lto = true FIXME: at the moment is  broken even if lto is true, commenting so that testing in rust is faster
debug = true
debug-assertions = true
panic = 'abort'
